---
# Perform all neccessary setup tasks

- name: Install required packages
  package:
      name: "{{ item }}"
      state: latest
  with_items: "{{ packages }}"

- name: Load Kernelmodules
  modprobe:
      name: vboxdrv
      state: present

- name: Ensure existence of vagrant diskfile directory
  file:
      path: "{{ vagrant_diskdir }}"
      state: directory
      owner: '{{ deploying_user }}'
      mode: 0700
  when:
      extra_disk

- name: Generate Vagranfile from template
  template:
      src: vagrantfile.jinja2
      dest: ./Vagrantfile
      owner: '{{ deploying_user }}'
      mode: 0700
