---
# Perform all neccessary setup tasks
- name: Ensure packages for deployment tasks are present on debian systems as well
  script: basedeploy.sh
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install required packages
  package:
      name: "{{ item }}"
      state: latest
  with_items: "{{ packages }}"

- name: configure ssh
  debug: msg="coming soon"

- name: configure ufw
  debug: msg="coming soon"
